---
database:
  username: blabla
  password: mauhauhua
  port: 3306
variables:
  title: "Ulyaoth Chat"
  email: "webmaster@ulyaoth.net"
  cookiename: ulyaoth
ranks:
  member_rank: 0
  paid_member_rank: 1
  max_paid_member_rank: 100
  moderator_rank: 120
  max_moderator_rank: 170
  staff_rank: 180
  max_staff_rank: 190
  admin_rank: 200